[project]
name = "aya-burmese-expeditions"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pillow",
    "streamlit",
    "opencv-python",
    "numpy",
    "datasets>=2.13.2",
    "googletrans>=3.0.0",
    "google-cloud-documentai>=3.3.0",
    "pdf2image>=1.17.0",
    "python-dotenv>=0.21.1",
    "cohere>=4.36",
    "litellm>=0.1.202",
    "selenium>=4.11.2",
    "webdriver-manager>=4.0.2",
    "gradio-client>=0.2.6",
]
