[project]
name = "burmese-ocr"
version = "0.1.0"
description = "A tool for OCR of Burmese text"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pytesseract",
    "pillow",
    "streamlit",
    "opencv-python",
    "numpy",
    "datasets>=2.13.2",
    "googletrans>=3.0.0",
    "google-cloud-documentai>=3.3.0",
    "pdf2image>=1.17.0",
    "python-dotenv>=0.21.1",
]
