[project]
name = "ayamytk"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11.12"
dependencies = [
    "pillow",
    "streamlit",
    "opencv-python",
    "numpy",
    "datasets>=2.13.2",
    "googletrans>=3.0.0",
    "google-cloud-documentai>=3.3.0",
    "pdf2image>=1.17.0",
    "python-dotenv>=0.21.1",
    "litellm>=0.1.202",
    "selenium>=4.11.2",
    "webdriver-manager>=4.0.2",
    "gradio-client>=0.2.6",
    "pymupdf>=1.22.5",
    "pymyanlp @ git+https://github.com/Rickaym/pymyanlp",
    "networkx>=2.6.3",
    "matplotlib>=3.5.3",
    "scipy>=1.7.3",
    "fastavro==1.10.0",
    "cohere>=4.57",
    "tables>=3.10.1",
    "pandas>=1.1.5",
    "tabulate>=0.9.0",
]

[tool.uv.sources]
pymyanlp = { git = "https://github.com/Rickaym/pymyanlp" }


[tool.setuptools.packages.find]
include = ["ayamytk*"]
